# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-dubnium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-dubnium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "5800:5800"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59-dubnium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "5801:5800"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  tests:
    image: global-app/rspec
    build: .
    depends_on:
      - firefox
      - chrome
    ports:
      - "5000:5000"
    environment:
      - DRIVER=remote_chrome
      - DOCKER_COMPOSE_WAIT=30
      - TESTS_TO_RUN=${TESTS_TO_RUN}
    volumes:
      - .:/tests
    command:
      - |
          rspec spec/$${TESTS_TO_RUN}
          allure serve reports/allure-results -p 5000
